### ISSUE TITLE
upload to scipy-wheels-nightly

### ISSUE THREAD

**Issue by keewis** [MacPython/matplotlib-wheels#13]
Continuing from pydata/xarray#4256.

Here's an example for uploading to https://pypi.anaconda.org/scipy-wheels-nightly/: https://github.com/MacPython/pandas-wheels/blob/master/azure/posix.yml and to get a token:
> I believe that @ogrisel can add you to the organization on anaconda.org so that you can create a key to upload to packages.

cc @tacaswell, @TomAugspurger, @ogrisel

**Comment by keewis** [comment]
gentle ping, @tacaswell?

**Comment by QuLogic** [comment]
We're waiting for a reply from @ogrisel.

**Comment by keewis** [comment]
If I read the [mailing list](https://mail.python.org/pipermail/numpy-discussion/2020-August/080923.html) correctly, it seems @mattip might also be able to help you with that

**Comment by mattip** [comment]
I wonder if we should move to [organization-wide secrets](https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#creating-encrypted-secrets-for-an-organization) so any repo in this org could upload. I don't see the "settings" option on the [organization](https://github.com/MacPython), so someone who is an admin would have to do it. @matthew-brett thoughts?

**Comment by matthew-brett** [comment]
@mattip - I've made you an owner of the MacPython organization - can you see the settings now?

**Comment by mattip** [comment]
I added two organization wide secrets, in the mean time I enabled them only for this repo. So once you figure out how to use them, any other repo here can copy your code and request that an admin enble them.
key | for url | intention
--- | --- | ---
`MULTIBUILD_WHEELS_STAGING_ACCESS` | https://anaconda.org/multibuild-wheels-staging | staging wheels before deployment
`SCIPY_WHEELS_NIGHTLY_ACCESS` | https://anaconda.org/scipy-wheels-nightly/ | weekly dev packages for testing by the wider community

**Comment by keewis** [comment]
gentle ping, @QuLogic, @tacaswell. Any updates on this?

**Comment by mattip** [comment]
The organization-wide tokens will only work on github actions. The workflow here is based on travis-ci, so tokens will have to be added via https://travis-ci.org/github/MacPython/matplotlib-wheels -> More Options -> Settings (available to admins). Once the tokens are added, the yaml should look something like the [code from scipy](https://github.com/MacPython/scipy-wheels/blob/master/.travis.yml#L234)

**Comment by janaknat** [comment]
@tacaswell @mattip I've got a PR to change the upload process at https://github.com/MacPython/matplotlib-wheels/pull/14

**Comment by QuLogic** [comment]
So do we need to get the tokens from someone first?

**Comment by mattip** [comment]
I can add a repo admin to the owner group at ananconda to create the tokens. I think the active admin here is @tacaswell, so either they need to tell me their user name on anaconda.org or they need to make someone else an admin here and that person needs to tell me their user name on anaconda.org. Also: you might want to consider moving off travis.

**Comment by janaknat** [comment]
@mattip If the concern with Travis is due to the change in the pricing model I can provide some additional info. Travis infrastructure was being abused by free accounts setting up projects that involve cryptocurrency mining and TOR nodes. To counter this there was a change in the way things are done. Open source projects can contact travis and get extra credits towards their usage. Please contact support@travis-ci.com with your name and account URL (such as travis-ci.com/github/[your account name])

**Comment by mattip** [comment]
@janaknat thanks for the info. The onus of needing to ask for credits whenever they run out, together with needing to give travis-ci.com access read/write access to all my private and public repos just to log on, is too much for me. Unfortunately I can't entirely disengage from travis since so far they are the only ones to provide powerPC and s390x builders, but once that is solved I think I will prefer other CI services.

**Comment by tacaswell** [comment]
Please move this discussion to https://github.com/matplotlib/matplotlib/issues/9994
